name: "VetVR Chaneg Request Report"
description: "File a change request report"

body:
- type: dropdown
  id: major-version
  attributes:
    label: Major Version
    description: Choose a version
    options:
      - MVP Demo
      - MVP
      - Anesthesia Machine Exam
  validations:
    required: true
- type: input
  id: minorversion
  attributes:
    label: Minor Version
    description: Put down minor version if there is one
- type: dropdown
  id: headset
  attributes:
    label: Headset
    description: Choose a headset
    options:
      - HP reverb G2
      - Oculus Quest II and newer generations (tethered) 
      - Samsung Odyssey 
      - Valve Index 
      - Vive HTC1 and newer generations
      
- type: dropdown
  id: scene
  attributes:
    label: Scene
    description: What scene are you talking about?
    options:
      - Lobby
      - Palperbral Reflex
      - ECG
      - Stethscope
      - Medicine Dose
      - Ultrasound
      - Porcupine Scenario
      - Wrist Diagnostics
      - Laceration Scenario
      - Mooncake Scenario
      - Atlas Scenario
      - Other
  validations:
    required: true
- type: dropdown
  id: changerequestarea
  attributes:
    label: Change Request Area
    description: 
    options:
      - Animation
      - Immersion
      - Level Progression
      - Quality of Life
      - UX/UI
      - Others
  validations:
    required: true
- type: dropdown
  id: changerequestpriority
  attributes:
    label: Change Request Priority
    description: 
    options:
      - High
      - Medium
      - Low
- type: textarea
  id: what-to-change
  attributes:
    label: What are you looking to change?
    description: 
    placeholder: Tell us how yu wnat this work!
    value: 
  validations:
    required: true
- type: dropdown
  id: issuestatus
  attributes:
    label: Issue Status
    description: 
    options:
      - Submitted
      - Pending Review
      - Completed
      - Deleted
      - Works as Designed
      - Not Reproducible
  validations:
    required: true
- type: markdown
  attributes:
    value: |
       Thanks for taking the time to fill out this change request report!
- type: checkboxes
  id: developers
  attributes:
    label: Developer(s) assigned
    description: You may select more than one.
    options:
      - label: E
      - label: Logan
      - label: Morgan
- type: textarea
  id: notes
  attributes:
    label: Notes
    description: Leave your notes here
    placeholder: "Leave any helpful notes here"
