name: "VetVR Bug Report"
description: "File a bug report"
title: "Bug"
labels: "Bug"

body:
- type: dropdown
  id: major-version
  attributes:
    label: Major Version
    description: Choose a version
    options:
      - MVP-Demo
      - MVP
      - Anesthesia-Machine-Exam
- type: dropdown
  id: Headset
  attributes:
    label: Headset
    description: Choose a headset
    options:
      - HP reverb G2 
      - Vive HTC1 and newer generations 
      - Samsun Odyssey 
      - Oculus Quest II and newer generations (tethered) 
      - Valve Index 
- type: checkboxes
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: Black cat
- type: dropdown
  id: scene
  attributes:
    label: Scene
    description: What scene are you in?
    options:
      - Lobby
      - Palperbral Reflex
      - ECG
      - Stethscope
      - Medicine Dose
      - Ultrasound
      - Porcupine Scenario
      - Wrist Diagnostics
      - Laceration Scenario
      - Mooncake Scenario
      - Atlas Scenario
- type: dropdown
  id: issuetype
  attributes:
    label: Issue Type
    description: What scene are you in?
    options:
      - Immersion
      - Quality of Life
      - UX/UI
      - Level Progression
- type: markdown
  attributes:
    value: |
       Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
